#!/usr/bin/env bash
XSECURELOCK_PASSWORD_PROMPT=cursor \
XSECURELOCK_SHOW_USERNAME=1 \
XSECURELOCK_SHOW_DATETIME=1 \
XSECURELOCK_SAVER=saver_mpv \
XSECURELOCK_IMAGE_DURATION_SECONDS=600 \
XSECURELOCK_LIST_VIDEOS_COMMAND="find ~/Pictures -type f" \
xsecurelock



